print("hello world")
print("hello Chuks")
print("Let's go!!")
print("another one")
print("I went to work haven today")
print("Did this on Tuesday")
print("Did this on Wednesday")
print("Did this on Thursday")
print("Did this on Friday")
print("Did this on Saturday")
print("Did this on Sunday")